name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Build frontend
        run: |
          cd frontend
          npm run build

      - name: Archive frontend dist
        run: |
          tar -czf frontend-dist.tar.gz -C frontend dist

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend-dist.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: .

      - name: Upload dist to EC2 via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          source: "frontend-dist.tar.gz"
          target: "/home/${{ secrets.EC2_USER }}/ReadWatch/frontend/"

      - name: Remote Deploy Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            DEPLOY_PATH=/home/${{ secrets.EC2_USER }}/ReadWatch/frontend
            cd $DEPLOY_PATH
            rm -rf dist
            tar -xzf frontend-dist.tar.gz
            rm frontend-dist.tar.gz
            sudo chown -R www-data:www-data $DEPLOY_PATH/dist
            sudo systemctl reload nginx || sudo service nginx reload
